Badger\Bundle\GameBundle\Entity\BadgeCompletion:
    type: entity
    table: badge_completions
    repositoryClass: Badger\Bundle\GameBundle\Doctrine\Repository\BadgeCompletionRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        completionDate:
            type: datetime
            nullable: false
        pending:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: Badger\Bundle\UserBundle\Entity\User
            cascade: ['persist']
            joinColumn:
                user_id:
                    referencedColumnName: id
                onDelete: cascade
        badge:
            targetEntity: Badger\Bundle\GameBundle\Entity\Badge
            inversedBy: completions
            joinColumn:
                badge_id:
                    referencedColumnName: id
                onDelete: cascade
