parameters:
    badger.game.badge.factory.class: Badger\Bundle\GameBundle\Factory\BadgeFactory
    badger.game.badge_completion.factory.class: Badger\Bundle\GameBundle\Factory\BadgeCompletionFactory
    badger.game.quest.factory.class: Badger\Bundle\GameBundle\Factory\QuestFactory
    badger.game.quest_completion.factory.class: Badger\Bundle\GameBundle\Factory\QuestCompletionFactory
    badger.game.adventure.factory.class: Badger\Bundle\GameBundle\Factory\AdventureFactory
    badger.game.adventure_step_completion.factory.class: Badger\Bundle\GameBundle\Factory\AdventureStepCompletionFactory
    badger.game.tag.factory.class: Badger\Bundle\GameBundle\Factory\TagFactory

services:
    badger.game.badge.factory:
        class: '%badger.game.badge.factory.class%'

    badger.game.badge_completion.factory:
        class: '%badger.game.badge_completion.factory.class%'

    badger.game.quest.factory:
        class: '%badger.game.quest.factory.class%'

    badger.game.quest_completion.factory:
        class: '%badger.game.quest_completion.factory.class%'

    badger.game.adventure.factory:
        class: '%badger.game.adventure.factory.class%'

    badger.game.adventure_step_completion.factory:
        class: '%badger.game.adventure_step_completion.factory.class%'

    badger.game.tag.factory:
        class: '%badger.game.tag.factory.class%'
