services:
    badger.game.remover.badge:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Badge'

    badger.game.remover.badge_completion:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\BadgeCompletion'

    badger.game.remover.quest:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Quest'

    badger.game.remover.quest_completion:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\QuestCompletion'

    badger.game.remover.adventure:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Adventure'

    badger.game.remover.adventure_step_completion:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\AdventureStepCompletion'

    badger.game.remover.tag:
        class: '%badger.storage_utils.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Tag'
