parameters:
    badger.game.unlocker.badge.class: Badger\Bundle\GameBundle\Unlocker\BadgeUnlocker

services:
    badger.game.unlocker.badge:
        class: '%badger.game.unlocker.badge.class%'
        arguments:
            - '@badger.game.badge_completion.factory'
            - '@badger.game.repository.badge_completion'
            - '@badger.game.saver.badge_completion'
